### ISSUE TITLE
can we set a field "notes" in a password entry

### ISSUE THREAD

**Issue by monperrus** [valeriangalliat/firefox-sync-cli#1]
Hi,

Thanks a lot for your great posts about scripting Firefox Sync.

I'm a heavy user of the "notes" metadata in my password manager. However, I don't see such a field in Firefox or Lockwise.

Is that a UI problem or a data model problem? can we set a field "notes" in a user/password payload?

Thanks!

**Comment by valeriangalliat** [comment]
Hey! I don't think there's anything like "notes" in Lockwise, it only supports user/password

You could technically add any extra field in the JSON payloads where the website/user/password is already stored, but you would need your own client to manage it, it won't show in the Firefox browser and apps

**Comment by monperrus** [comment]
Thanks for your answer.

> You could technically add any extra field in the JSON payloads where the website/user/password is already stored

Interesting. Does it mean that the server is fully agnostic to the JSON payload?

**Comment by valeriangalliat** [comment]
Yep that's what it seemed like! I didn't test extensively how the Firefox apps behave with added data though, I think they happily show entries as long as they contain all the "normal" fields but I'm not sure what happens to extra fields when editing an entry from Lockwise

**Comment by monperrus** [comment]
Cool. Since [Lockwise has been discontinued](https://support.mozilla.org/en-US/kb/end-of-support-firefox-lockwise) there may be an opportunity to fork the Android app and add support for a "notes" field.

Thanks a lot  @valeriangalliat
